name: example
description: Example for flutter_translate_gen

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_translate_annotations:
    git:
      url: https://github.com/celltrak/Flutter-Translate-Annotations.git

dev_dependencies:
  flutter_translate_gen:
    path: ../
  build_runner: ^2.1.10
